### ISSUE TITLE
Crashes on malformed input in MRTTblDumpV2RibHeader::init

### ISSUE THREAD

**Issue by fgeek** [cawka/bgpparser#1]
I found segmentation fault from bgpparser with [american fuzzy lop](http://lcamtuf.coredump.cx/afl/) fuzzer. Fuzzed sample can be fetched from here: http://bugs.fi/media/afl/bgpparser/bgpparser-segfault with SHA1 2178b6a626020db1c4e41fc8ae28c8886081bc8b.

I used latest Git revision:

```
commit 723b084364ec0c9d76a13be44014b65d3bfe21f0
Author: Alexander Afanasyev <alexander.afanasyev@ucla.edu>
Date:   Wed Apr 13 16:47:42 2011 -0700
```

GDB backtrace below:

```
(gdb) run --file bgpparser-segfault
Starting program: /home/fgeek/bgpparser-temp/bin/bgpparser2 --file bgpparser-segfault
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
bgpparser2: MRTTblDumpV2RibHeader.cpp:88: void MRTTblDumpV2RibHeader::init(std::istream&): Assertion `_peerIndexTbl.get()!=__null' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff603b107 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff603b107 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff603c4e8 in __GI_abort () at abort.c:89
#2  0x00007ffff6034226 in __assert_fail_base (fmt=0x7ffff616ace8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x7ffff6c20b23 "_peerIndexTbl.get()!=__null", file=file@entry=0x7ffff6c20b09 "MRTTblDumpV2RibHeader.cpp", 
    line=line@entry=88, 
    function=function@entry=0x7ffff6c21140 <MRTTblDumpV2RibHeader::init(std::istream&)::__PRETTY_FUNCTION__> "void MRTTblDumpV2RibHeader::init(std::istream&)") at assert.c:92
#3  0x00007ffff60342d2 in __GI___assert_fail (assertion=0x7ffff6c20b23 "_peerIndexTbl.get()!=__null", file=0x7ffff6c20b09 "MRTTblDumpV2RibHeader.cpp", 
    line=88, 
    function=0x7ffff6c21140 <MRTTblDumpV2RibHeader::init(std::istream&)::__PRETTY_FUNCTION__> "void MRTTblDumpV2RibHeader::init(std::istream&)")
    at assert.c:101
#4  0x00007ffff6c1899f in MRTTblDumpV2RibHeader::init (this=this@entry=0x665090, input=...) at MRTTblDumpV2RibHeader.cpp:88
#5  0x00007ffff6c1a4d9 in MRTTblDumpV2RibIPv6Unicast::MRTTblDumpV2RibIPv6Unicast (this=0x665090, peer_tbl=..., header=..., input=...)
    at MRTTblDumpV2RibIPv6Unicast.cpp:47
#6  0x00007ffff6c1313e in MRTCommonHeader::newMessage (input=..., indexTbl=...) at MRTCommonHeader.cpp:191
#7  0x0000000000412121 in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:201
```

**Comment by cawka** [comment]
Thanks for the reporting the issue.
