### ISSUE TITLE
Segmentation fault with bgpparser

### ISSUE THREAD

**Issue by jack8daniels2** [cawka/bgpparser#2]
bgpparser built on OSX, crashes with a segmentation fault when parsing the following MRT file.
http://archive.routeviews.org/bgpdata/2015.08/UPDATES/updates.20150801.0000.bz2
It only happens when converting MRT to XML format, but doesn't happen with short format.

**Comment by jack8daniels2** [comment]
Same problem on debian. Stack trace here -

```
Program received signal SIGSEGV, Segmentation fault.
AttributeTypeAggregatorDumper::genXml (this=<optimized out>) at ../dumper/AttributeTypeAggregatorDumper.cpp:69
69                      FORMAT_IPv4_ADDRESS(attr->getAggregatorBGPSpeakerIPAddress().ipv4).c_str());
(gdb) print attr
$1 = std::shared_ptr (empty) 0x0
(gdb) 
(gdb) bt
#0  AttributeTypeAggregatorDumper::genXml (this=<optimized out>) at ../dumper/AttributeTypeAggregatorDumper.cpp:69
#1  0x000000000041e6aa in BGPAttributeDumper::genXml (this=<optimized out>) at ../dumper/BGPAttributeDumper.cpp:87
Python Exception <type 'exceptions.ValueError'> Cannot find type const std::list<std::shared_ptr<BGPAttribute>, std::allocator<std::shared_ptr<BGPAttribute> > >::_Node: 
#2  0x000000000042377a in BGPUpdateDumper::genUpdateAttributesNode (this=this@entry=0x19ff5d0, pathAttributes=std::list) at ../dumper/BGPUpdateDumper.cpp:106
#3  0x0000000000423ae3 in BGPUpdateDumper::genXmlAsciiNode (this=0x19ff5d0) at ../dumper/BGPUpdateDumper.cpp:127
#4  0x000000000041f69f in BGPDumper::genXmlAsciiMsg (this=0x19ff5d0) at ../dumper/BGPDumper.cpp:105
#5  0x000000000041ff04 in BGPMessageDumper::genXml (this=0x19f9d70) at ../dumper/BGPMessageDumper.cpp:102
#6  0x0000000000428469 in MRTBgp4MPMessageDumper::genXml (this=0x19f9fe0) at ../dumper/MRTBgp4MPMessageDumper.cpp:66
#7  0x000000000042d3cc in procMsg (dumper=..., flag_format=1, flag_newline=1, flag_bgpdump=<optimized out>) at ../dumper/mrt2xml.cpp:133
#8  0x000000000041456c in main (argc=<optimized out>, argv=<optimized out>) at ../dumper/mrt2xml.cpp:356
```
